### ISSUE TITLE
Example files

### ISSUE THREAD

**Issue by schroef** [docsforadobe/javascript-tools-guide#2]
I was wondering where we can find these example files talked about on this page?

https://extendscript.docsforadobe.dev/user-interface-tools/code-examples-for-scriptui.html

**Comment by Klustre** [comment]
They were part of the Extendscript Toolkit CC installation. The app has long been deprecated, but if you're on Windows I believe you can still install it from the Creative Cloud app. If you're on Mac it might not show at all.

The samples will be in `C:\Program Files (x86)\Adobe\Adobe ExtendScript Toolkit CC\SDK\Samples\javascript`

**Comment by Klustre** [comment]
We've asked Adobe if we can host the files. For now you can download ESTK here:
- Windows: http://download.adobe.com/pub/adobe/devnet/scripting/estk/AdobeExtendScriptToolkit3.5.0-mul.zip
- MacOS: http://download.adobe.com/pub/adobe/devnet/scripting/estk/AdobeExtendScriptToolkit3.5.0-mul.dmg

**Comment by Klustre** [comment]
We should link from [this page](https://extendscript.docsforadobe.dev/user-interface-tools/code-examples-for-scriptui.html#code-examples-for-scriptui) to [this paragraph](https://extendscript.docsforadobe.dev/introduction/extendscript-overview.html#example-code) once #1 is merged, so people can install the examples. If we are allowed to host the examples, we can simply link to a zip instead.

**Comment by ErinFinnegan** [comment]
So, those devnet links aren't going to keep working... I've moved downloads here: https://github.com/Adobe-CEP/CEP-Resources/tree/master/ExtendScript-Toolkit 

However, you can't run it on macOS greater than Catalina...

🤔 We could probably move the code samples somewhere more visible.

**Comment by SheetJSDev** [comment]
@ErinFinnegan the discussed installers are not included in the repo:

| name and link | md5 |
|:-|:-|
| [AdobeExtendScriptToolkit3.5.0-mul.dmg](http://download.adobe.com/pub/adobe/devnet/scripting/estk/AdobeExtendScriptToolkit3.5.0-mul.dmg ) | 6152e40145c94747883d6ccd5437221a | |
| [AdobeExtendScriptToolkit3.5.0-mul.zip](http://download.adobe.com/pub/adobe/devnet/scripting/estk/AdobeExtendScriptToolkit3.5.0-mul.zip) | afe36a7bf09ebd6b50482c83b4ecc70c |

Would it be possible to add those as well?

**Comment by Klustre** [comment]
@SheetJSDev Those are already added by your PR #1. 

I've just added the github mirror to the docs (see above commit).

**Comment by SheetJSDev** [comment]
The [GitHub mirror](https://github.com/Adobe-CEP/CEP-Resources/tree/master/ExtendScript-Toolkit) includes "AdobeExtendScriptToolkit_4_LS22", which is Adobe ExtendScript Toolkit CC (4.0.0.1 ExtendScript 4.5.5 ScriptUI 6.2.2).

[Direct links to older versions can be found in an older snapshot of the ESTK page](https://web.archive.org/web/20170429150810/http://www.adobe.com/devnet/scripting/estk.html).  The following downloaders are still live:

ESTK 2.0.2 (CS3): [mac](http://download.macromedia.com/pub/developer/bridge/sdk/AdobeExtendScriptToolkit2.0.2All.dmg) [win](http://download.macromedia.com/pub/developer/bridge/sdk/AdobeExtendScriptToolkit2.0.2All.zip)

ESTK 3.0 (CS4): [mac](http://download.macromedia.com/pub/developer/estk/sdk/AdobeExtendScriptToolkit3.0.0All.dmg) [win](http://download.macromedia.com/pub/developer/estk/sdk/AdobeExtendScriptToolkit3.0.0All.zip)

ESTK 3.5 (CS5): [mac](http://download.macromedia.com/pub/developer/estk/sdk/AdobeExtendScriptToolkit3.5.0-mul.dmg) [win](http://download.macromedia.com/pub/developer/estk/sdk/AdobeExtendScriptToolkit3.5.0-mul.zip)

None of these are in the GitHub mirror, hence the question.  Note: The ESTK 3.8 (CS6) installer was never on that page

**Comment by Klustre** [comment]
@SheetJSDev Let's stay on the topic of the ticket. To conclude, keeping a list of long deprecated software doesn't make sense. Linking to the [latest version](https://github.com/Adobe-CEP/CEP-Resources/tree/master/ExtendScript-Toolkit) is enough.

**Comment by ErinFinnegan** [comment]
@schroef I've uploaded the files here: https://github.com/Adobe-CEP/CEP-Resources/tree/master/ExtendScript-Toolkit/Samples
